spring:
  application:
    name: dailyfeed-search
  data:
    mongodb:
      host: ${MONGODB_HOST:alpha300.sz30zco.mongodb.net}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USER:dailyfeed-search}
      password: ${MONGODB_PASSWORD:hitEnter!!!}
      protocol: mongodb+srv
      uri: mongodb+srv://dailyfeed-search:hitEnter!!!@alpha300.sz30zco.mongodb.net/dailyfeed?retryWrites=true&w=majority&appName=alpha300
app:
  dailyfeed-search:
    mongodb:
      database: dailyfeed